= How to deploy with an existing database

[IMPORTANT]
====
The provisioning part of BCD is now **deprecated** and will be **removed** ! We do not recommend using it.
====

By default, BCD provisions a database Docker container while deploying your Bonita stack. +
Alternatively, BCD also lets you connect your Bonita stack with an existing database server. The database vendor and version has to be supported by BCD though.

When the `bonita_db_host` variable is defined, BCD does not create a database container. Instead, BCD expects to connect to an existing database. +
The following variables are to be set accordingly:

* `bonita_db_vendor` - Vendor name in [postgres, mysql, oracle].
* `bonita_db_host` - Host name or IP address (eg. `postgres.a1bac2defghi.us-west-2.rds.amazonaws.com`).
* `bonita_db_port` - Port number (eg. `5432`).
* `bonita_db_admin_user` - Name of an existing Administrator user (aka. "Master username"). This user must be granted permissions to create the Bonita and Business Data Model (BDM) databases.
* `bonita_db_admin_pass` - Password of the Administrator user.

Example with Amazon RDS
// {.h2}

One typical use case is to deploy your Bonita stack using an https://aws.amazon.com/rds/[Amazon RDS] instance.

. Prior to creating your RDS instance, create and customize a https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithParamGroups.html[DB Parameter Group] in order to set database parameters for Bonita. Refer to Bonita documentation to check how to xref:{bonitaDocVersion}@bonita::database-configuration.adoc[Customize RDBMS to make it work with Bonita].
. Create your RDS instance using the DB parameter group created previously. Make sure the assigned security group allows access to the DB instance. +
Leave the *Database Name* field empty to not create a database. BCD will create required databases automatically.
. Report connection information into your BCD scenario:
 ** `bonita_db_host` - DB instance endpoint (eg. `postgres.a1bac2defghi.us-west-2.rds.amazonaws.com`).
 ** `bonita_db_port` - Database Port (eg. `5432`).
 ** `bonita_db_admin_user` - Master Username.
 ** `bonita_db_admin_pass` - Master Password.
