= Getting started
:description: The BCD java CLIs install from Bonita Artifact Repository.

This page describes how to download the java CLIs to start your journey with Bonita Continuous Delivery.

IMPORTANT: First make sure your maven installation is configured to access Bonita Artifact Repository !

== Builder installation guide

You can download the `bonita-la-builder` with a simple maven command (that will use the credentials declared in your maven settings.xml configuration file).

.Download with maven
[source, bash]
----
mvn dependency:copy -Dartifact=com.bonitasoft.tools:bonita-la-builder:<bonita.runtime.version>:jar:exec -Dmdep.stripVersion -Dmdep.stripClassifier -DoutputDirectory=./
----

Just use the CLI jar once downladed :

.Execution sample
[source, bash]
----
java -jar bonita-la-builder.jar build -e production <path to the bonita project>
----

You can call `bonita-la-builder` with the `--help` option to get available options and commands as follows:

[source,bash]
----
bonita@bcd-controller:~/bonita-continuous-delivery$ java -jar bonita-la-builder -h
Usage: java -jar bonita-la-builder-<bonita.runtime.version>-exec.jar [command] [command options]
  Commands:
    build      Build a Bonita project
      Usage: build [options] <path/to/bonita/project>
        Options:
          -P, --activate-profiles
            Comma-delimited list of maven profiles to activate
          -B, --batch-mode
            Run in non-interactive (batch) mode
            Default: false
          -X, --debug
            Produce execution debug output
            Default: false
          --disable-color
            Disable color output (enabled by default)
            Default: false
          -e, --environment
            Select the target environment configuration
            Default: Local
          --ignore-version-conflict
            Do not check project version and builder version compatibility
            Default: false
          -o, --output
            Output archive file name. Default is <folder-name>-<timestamp>.zip

    extract      Extract parameters form a Bonita configuration archive
      Usage: extract [options] <path/to/configuration-file.bconf>
        Options:
          --without-value
            Only extract parameters without value
            Default: false
          -o
            Output file
            Default: parameters.yml

    merge      Merge parameters into a Bonita configuration archive
      Usage: merge [options] <path/to/configuration-file-to-update.bconf>
        Options:
        * -i
            Input parameter file
          -o
            Output file. By default, the  given configuration file is overwritten.
----

== Deployer installation guide

Same approach applies. Download the CLI jar first, then use it.

.Download with maven
[source, bash]
----
mvn dependency:copy -Dartifact=com.bonitasoft.deployer:bonita-la-deployer:<deployer.version>:jar -Dmdep.stripVersion -Dmdep.stripClassifier -DoutputDirectory=./
----

.Execution sample
[source, bash]
----
java -jar bonita-la-deployer.jar -f <path to the bonita archive to deploy> -t http://localhost:8080/bonita -u install -p install
----

You can call `bonita-la-builder` with the `--help` option to get available options and commands as follows:

[source,bash]
----
bonita@bcd-controller:~/bonita-continuous-delivery$ java -jar bonita-la-deployer -h
usage: java -jar bonita-la-deployer-x.y.z.jar [-bc <bonita-configuration>] [--debug] [--development]
       [--disable-certificate-check] [-f <file>] [-h] [--http-timeout <http-timeout>] [-p <password>] [-t <targetUrl>]
       [-u <username>]

Deploy an Application Archive and/or Application Configuration to a Bonita platform
 -bc,--bonita-configuration <bonita-configuration>   the Application Configuration to deploy
    --debug                                          activate debug logs
    --development                                    Deploy for development environment (Eg. processes / profiles are
                                                     replaced if existing, ...)
    --disable-certificate-check                      disable all certificate validation when connecting to a https
                                                     server. Use this option when a self-signed certificate is used on
                                                     the target server.
 -f,--file <file>                                    the Application Archive to deploy
 -h,--help                                           print this message
    --http-timeout <http-timeout>                    the timeout (in seconds, default to 120) for http interactions
                                                     (read and write) with Bonita
 -p,--password <password>                            password to use to connect to Bonita
 -t,--targetUrl <targetUrl>                          url of the Bonita platform
 -u,--username <username>                            username to use to connect to Bonita

Examples:
java -jar bonita-la-deployer-x.y.z.jar -f <application_archive_zip_path>
java -jar bonita-la-deployer-x.y.z.jar -f <application_archive_folder_path> -t http://myhost/bonita
----

TIP: For both CLIs you can use the https://www.mojohaus.org/exec-maven-plugin/[exec-maven-plugin] to include `build` and/or `deploy` step in the bonita project lifecycle (starting from version 7.13.x, a bonita project is a maven project)
