= How to manage Bonita licenses

[IMPORTANT]
====
The provisioning part of BCD is now **DEPRECATED** and will be **REMOVED** ! We do not recommend using it.
====

This tutorial describes how to manage Bonita licenses from the command line using BCD. +
This feature lets you generate licenses programmatically for your Bonita Studio or Bonita Server.

== Prerequisites

To use this feature, you need to prepare a link:scenarios[scenario file] with the following required information:

* The `bonita_version` variable
* xref:scenarios.adoc#licensing_variables[licensing variables in scenarios]

NOTE: An example scenario is provided with the *scenarios/manage_licenses.yml.EXAMPLE* file with required variables to manage
Bonita licenses with BCD.


== Generating a new license

You can generate a new license providing a *Request Key*. Read more about Bonita licenses and how to generate a request key on this xref:{bonitaDocVersion}@bonita::licenses.adoc#_get_a_new_license[documentation page].

NOTE: The request key has to be generated on the host where your Bonita Studio or Bonita Server will be running.


Assuming your request key is `(CIVpYDRB8bhouXdWadLY1M9TVctwYUYu)`, here is an example usage of the `bcd license generate` command:

[source,bash]
----
$ bcd -s scenarios/euwest1_performance.yml -y license generate -k '(CIVpYDRB8bhouXdWadLY1M9TVctwYUYu)' -o /path/to/output_directory
----

WARNING: The output directory (`/path/to/output_directory` in the above example) is related to your BCD Controller Docker container. +
In order to persist the generated licenses after exiting the BCD Controller, you may use a bind-mounted output directory. Still, you may copy your generated licenses while the BCD controller is running.


== Revoking a license

You can revoke a Bonita license providing the path to a license file.

NOTE: Revoking a license will make your license inactive and it will delete the license file you have provided. +
This operation releases a _slot_ to generate a new license as authorized by your Bonita subscription.


Here is an example usage of the `bcd license revoke` command:

[source,bash]
----
$ bcd -s scenarios/euwest1_performance.yml -y license revoke -p /path/to/bonita_license_file.lic
----
