= Release notes

== What's new in 3.6.0

=== Features

- Added xref:{testToolkitVersion}@test-toolkit::process-testing-overview.adoc[test toolkit] support in BCD commands
- Added logback config file (`/usr/local/lib/logback.xml`) to offer finer la-deployer log management.

=== Breaking changes

* Some scenario variables have been renamed to a more coherent name  (see xref:scenarios.adoc[])
** renamed : `bonita_tenant_login` to `bonita_technical_username`
** renamed : `bonita_tenant_password` to `bonita_technical_password`

=== Deprecations

* `Ansible Vault` integration will be removed in the next release. +
The tool is still present so you can decrypt your files but it will be removed in the next releases. You should now rely on the secret management offered by your environment (https://docs.github.com/en/actions/security-guides/encrypted-secrets[Github], https://docs.gitlab.com/charts/installation/secrets.html[Gitlab], https://support.atlassian.com/bitbucket-cloud/docs/variables-and-secrets/[BitBucket], https://www.jenkins.io/doc/developer/security/secrets/[Jenkins], etc.)

=== Updates

* Docker controller image now based on `maven:3.8-jdk-11-slim`
* Python 3.8 => Python 3.9
* click: 7.1.2 => 8.0.4
* click-didyoumean: 0.0.3 => 0.3.0
* more-itertools: 8.6.0 => 8.12.0
* packaging: 20.4 => 21.3
* progress: 1.5 => 1.6
* PyYAML: 5.3.2 => 6.0

=== Removal

==== Python packages

* configParser
* cryptography
* idna
* Jinja2
* pycrypto
* tabulate
* requests
* urllib3

=== Fixes

* Remove the `docker-compose.override.yml.EXAMPLE`: we now use a single docker-compose file

== What's new in 3.5.0

=== Breaking changes

* As announced in version 3.4.4, `stack` and `license` commands are now removed from the CLI. +
 As a result, scenario files must be updated since a lot of parameters are now obsolete and a few remains mandatory (see xref:scenarios.adoc[])
* For the same reason, `openssh-client` package was removed from the docker controller image. +
You can re-add this package if needed by building a custom image of the controller.

.Sample custom BCD Controller with ssh client
[source,docker]
----
FROM quay.io/bonitasoft/bcd-controller:{bcdVersion}

USER root
RUN apt update && apt install -y openssh-client
USER bonita
----

=== Technology upgrade

- java => 11.0.12+7
- maven => 3.8.2

=== Updates

* chore(deps): bump urllib3 from 1.26.4 to 1.26.5 in bcd-cli
* feat(bonita): update support for bonita version 7.13.0

=== Removals

==== System packages

* openssh-client
* ttf-dejavu
* gcc
* g++

== What's new in 3.4.5

=== Features

* chore(deps): upgrade bonita-license to 1.4.2 for better license generation handling.

=== Fix

* fix(jdk11): fix jdk build failing because of gpg keys

WARNING: Since BCD 3.4.3, only the two last BCD Controller images are now available on quay.io, older images will be removed.
