= Release notes

== What's new in 3.5.0

=== Breaking changes

* As announced in version 3.4.4, `stack` and `license` commands are now removed from the CLI. +
 As a result, scenario files must be updated since a lot parameters are now obsolete and a few remains mandatory (see xref:scenarios.adoc[]) +
If you were using ansible `inventories/stack ids` to perform deployment (in your CI pipelines), you have to use the `url` of the targeted bonita instance instead. Ansible inventory was related to the `bcd stack` part and is now removed.

=== Technology upgrade

- java => 11.0.12+7
- maven => 3.8.2

=== Updates

* chore(deps): bump urllib3 from 1.26.4 to 1.26.5 in bcd-cli
* feat(bonita): update support for bonita version 7.13.0

== What's new in 3.4.5

=== Features

* chore(deps): upgrade bonita-license to 1.4.2 for better license generation handling.

=== Fix

* fix(jdk11): fix jdk build failing because of gpg keys

WARNING: Since BCD 3.4.3, only the two last BCD Controller images are now available on quay.io, older images will be removed.
