= Requirements and compatibility
:description: BCD requirements and compatibility matrix

This page describes which system requirements need to be met in order to use the Bonita Continuous Delivery CLIs. +
You will also find information about BCD CLIs and Bonita version compatibility.

== System requirements

The BCD features (build and deploy) are implemented by two standalone Java utilities, a maven plugin and a CLI.

IMPORTANT: You have to ensure that your maven installation is configured to access the xref:{bonitaDocVersion}@bonita:software-extensibility:bonita-repository-access.adoc[Bonita Artifact Repository]

=== Bonita project build

In versions 2023.2 and above, a Bonita project can be built xref:{bonitaDocVersion}@bonita:build-run:build-application.adoc[using Maven].

Building a bonita project requires: 

- https://adoptium.net/temurin/releases/?version=11[Java JDK 17]
- https://maven.apache.org/install.html[Apache Maven]

=== Bonita LA Deployer

The bonita-la-deployer program is simple java standalone CLI, so the only requirement is:

- https://adoptium.net/temurin/releases/?version=11[Java JDK 17]

== Version supported compatibility

[TIP]
====
BCD uses the technical Id of the platform. xref:{bonitaDocVersion}@bonita:version-update:product-versioning.adoc#_technical_id[You will find here the mapping between Bonita release and technical Id]
====

=== Bonita LA Deployer

The following table shows which bonita-la-deployer CLI versions support specific Bonita releases. +

|===
| bonita-la-deployer version | Bonita release
| 1.0.x       | 2021.2.x, 2022.1.x, 2022.2.x, 2023.1.x, 2023.2.x, 2024.1.x, 2024.2.x
|===

WARNING: If a Bonita release is not listed in the previous table, then it is not supported by the BCD offer.
