= Requirements and compatibility

This page describes which system requirements need to be met in order to use the Bonita Continuous Delivery Add-On. +
You will also find information about BCD and Bonita version compatibility.

NOTE: You must always upgrade to one of the latest two versions of the BCD Controller image. Check how to xref:upgrade_bcd.adoc[migrate from an earlier version of BCD]. Only the last two images are now available on quay.io, older images will be removed.

== System requirements

There are different environments where requirements are to be met for BCD:

* *Control host* - the host where your xref:bcd_controller.adoc[BCD controller] will run.
* *Jenkins server* - the server where BCD commands are executed by Jenkins Continuous Integration platform.

=== Control host

The *Docker Engine* must be up and running on your control host prior to using BCD. BCD is compatible with Docker version 17.04.0 and above.

You may have https://docs.docker.com/install/[Docker Community Edition (Docker CE)] or https://docs.docker.com/ee/supported-platforms/[Docker Enterprise Edition (Docker EE)] installed on your host to start using BCD.

NOTE: The Docker Engine may be installed on Linux, MacOS, Microsoft Windows or Cloud platforms as described in https://docs.docker.com/install/[Docker installation guide].

=== Jenkins server

BCD commands may be executed by a Jenkins agent (slave) which runs the BCD controller Docker container. +
Therefore the Jenkins server shall meet the same requirements as the Control host.

== Version supported compatibility

The following table shows which BCD versions support specific Bonita releases. +
This compatibility information is also specified in the xref:release_notes.adoc[Release notes] for each version of BCD.

|===
| BCD version | Bonita release
| 3.6.x       | 2021.1.x, 2021.2.x, 2022.1.x, 2022.2.x, 2023.1.x
|===


[TIP]
====
BCD uses the technical Id of the platform. xref:{bonitaDocVersion}@bonita:version-update:product-versioning.adoc#_technical_id[You will find here the mapping between Bonita release and technical Id]
====

WARNING: If a Bonita release is not listed in the previous table, then it is not supported by the BCD Add-On.

WARNING: Please note that from now on, sources that are to be compiled by BCD must be java 11 compliant.
