= Requirements and compatibility

This page describes which system requirements need to be met in order to use the Bonita Continuous Delivery Add-On. +
You will also find information about BCD and Bonita version compatibility.

NOTE: You must always upgrade to one of the latest two versions of the BCD Controller image. Check how to xref:upgrade_bcd.adoc[migrate from an earlier version of BCD]. Only the last two images are now available on quay.io, older images will be removed.

== System requirements

There are different environments where requirements are to be met for BCD:

* *Control host* - the host where your xref:bcd_controller.adoc[BCD controller] will run.
* *Bonita stack hosts* - the target hosts where your Bonita stack will be deployed using BCD.
* *Jenkins server* - the server where BCD commands are executed by Jenkins Continuous Integration platform.

=== Control host

The *Docker Engine* must be up and running on your control host prior to using BCD. BCD is compatible with Docker version 17.04.0 and above.

You may have https://docs.docker.com/install/[Docker Community Edition (Docker CE)] or https://docs.docker.com/ee/supported-platforms/[Docker Enterprise Edition (Docker EE)] installed on your host to start using BCD.

NOTE: The Docker Engine may be installed on Linux, MacOS, Microsoft Windows or Cloud platforms as described in https://docs.docker.com/install/[Docker installation guide].


=== Bonita stack hosts

WARNING: These requirements must be fulfilled when using BCD for *Provisioning*. They apply to target hosts where the Bonita stack will be deployed.


Bonita stack hosts may be running *on-premises* or in *cloud platforms* like https://aws.amazon.com/[Amazon Web Services (AWS)], https://azure.microsoft.com/[Microsoft Azure], https://cloud.google.com/[Google Cloud] or https://www.openstack.org/[OpenStack].

* with the AWS platform, BCD enables you to create and delete EC2 instances of the Bonita stacks automatically. To do so, read the xref:aws_prerequisites.adoc[AWS configuration for BCD tutorial].
* with the Azure platform, BCD enables you to create and delete Azure resources of the Bonita stacks automatically. To do so, read the xref:azure-prerequisites.adoc[Azure configuration for BCD tutorial].
* with other platforms, target hosts must be up and running prior to using BCD. Basic setup for target hosts is explained below.

The system requirements for the target hosts are as follows:

* Minimum hardware requirements: 1 CPU / 1GiB RAM / 8GiB storage (Equivalent to AWS EC2 `t2.micro` instance)
* Supported operating systems: Ubuntu-14.04, Ubuntu-16.04

Besides, the following technical requirements must be met:

* Target hosts must have *Internet access* in order to communicate with Bonitasoft License webservice. +
It is also required to install packages and to pull Docker public images for the database instance when applicable.
* Target hosts must be accessible from the BCD controller using *SSH public-key authentication*.
* The user configured to connect to the target hosts must have `sudo` or `root` privileges in order to install the Bonita stack.

=== Basic setup for target hosts

Here are the steps to manually install a target host for BCD:

1. Install one of the supported operating systems.
2. Create a user and grant `sudo` or `root` privileges.
3. Generate SSH keys for this user. The SSH private key has to be retrieved on your BCD controller and its path configured in your BCD scenario.

=== Jenkins server

BCD commands may be executed by a Jenkins agent (slave) which runs the BCD controller Docker container. +
Therefore the Jenkins server shall meet the same requirements as the Control host.

== Version compatibility

The following table shows which BCD versions support specific Bonita releases. +
This compatibility information is also specified in the xref:release_notes.adoc[Release notes] for each version of BCD.

|===
| BCD version | Bonita release

| 3.4.x | 7.9.5, 7.10.x, 7.11.x, 2021.1.x
|===

[TIP]
====
BCD uses the technical Id of the platform. https://documentation.bonitasoft.com/bonita/2021.2/version-update/product-versioning#_technical_id[You will find here the mapping between Bonita release and technical Id]
====

WARNING: If a Bonita release is not listed in the previous table, then it is not supported by the BCD Add-On.

WARNING: Please that from now on, sources that should be compiled by BCD must be java 11 compliant.

== Databases supported

The databases supported with BCD are: PostgreSQL, MySQL and Oracle. +
By default, BCD provisions a database Docker container while deploying your Bonita stack. +
But alternatively, BCD also lets you xref:deploy-with-existing-database.adoc[connect your Bonita stack with an existing database server (on-premise or in the cloud)].
