= BCD Scenario reference

[IMPORTANT]
====
The provisioning part of BCD is now **removed** ! Please clean up your scenario files.
====

Scenarios enable you to define parameter used for deployment on a Bonita instance. A scenario is a YAML Ansible variable file that BCD injects to the underlying Ansible playbooks. Its syntax basically follows http://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html[Ansible's YAML syntax].

The variables described in a scenario have precedence over those defined in the playbooks or the group vars. It is still possible to overload scenario variables with `--extra-vars` declaration in the `bcd` command line. For instance overloading `bonita_version` can be interesting if you want to test multiple versions of Bonita without duplicating scenario files.

NOTE: An example scenario file is provided in the *scenarios* directory:
*build_and_deploy.yml.EXAMPLE* - a scenario for living application management

Use this example to customize your scenario and save it with a `.yml` file extension.

== Bonita variables

The following parameters are specific to the Bonita instances.

|===
| Name | Mandatory | Default | Description | Sample

| bonita_version
| Y
| -
| Bonita version.
| 7.11.0

| bonita_url
a|
- N: for build command
- Y: for deploy command
| http://localhost:8080/bonita
| Bonita HTTP rool url.
| http://localhost:8080/bonita

| bonita_tenant_login
a|
- N: for build command
- Y: for deploy command
| install
| Bonita tenant login
| install

| bonita_tenant_password
a|
- N: for build command
- Y: for deploy command
| install
| Bonita tenant password
| install

|===

